# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1 -

### a) (I-A) es inversible

Al ser ($I$ - $A$) inversible, la solución obtenida para el vector $p$ es única. Veámoslo con la siguiente demostración, donde la inversa de ($I$ - $A$) también se conoce como L y se llama matriz de Leontief: <br>
$L \in \mathbb{R}^{n \times n}$, $d \in \mathbb{R}^{n \times 1}$ y $p \in \mathbb{R}^{n}$ Planteamos la ecuación $p = (I-A)^{-1}d$: <br>
   $$
   \left(\begin{matrix}
   p_1 \\
   \vdots \\
   p_n
   \end{matrix}\right)
   = \left(\begin{matrix}
   l_{11} & \cdots & l_{1n} \\
   \vdots & \ddots & \vdots \\
   l_{1n} & \cdots & l_{nn}
   \end{matrix}\right)
   \left(\begin{matrix}
   d_1 \\
   \vdots \\
   d_n
   \end{matrix}\right)
   $$
Resolviendo con multiplicación de matrices obtenemos:
$$
\begin{cases}
p_1 = l_{11} d_1 + l_{12} d_2 + ... + l_{1n} d_n \\
p_2 = l_{21} d_1 + l_{22} d_2 + ... + l_{2n} d_n \\
\vdots \\
p_n = l_{n1} d_1 + l_{n2} d_2 + ... + l_{nn} d_n \\
\end{cases}
$$
Lo que nos da un único valor para cada componente del vector $p$.  

### b) (I - A) es inversible y d = 0

Observando la ecuación planteada en el item $a)$, si reemplazamos a $d$ por el vector 0 obtenemos:
$$
\begin{cases}
p_1 = l_{11}*0 + l_{12}*0 + ... + l_{1n}*0 \\
p_2 = l_{21}*0 + l_{22}*0 + ... + l_{2n}*0 \\
\vdots \\
p_n = l_{n1}*0 + l_{n2}*0 + ... + l_{nn}*0 \\
\end{cases}
$$
Lo cual nos daría la solución trivial $p$ = 0. Esto significa que si sustituimos el vector $p=0$ en la ecuación, efectivamente cumple la igualdad:
$$
(I-A)*0=0
$$
Dado que cualquier matriz multiplicada por el vector cero da como resultado el vector cero, esta es una solución correcta. <br>
Además está solución es única ya que (I-A) es inversible. Esto significa que Nu(I-A) es vacío. Entonces, es correcto que la única solución del sistema planteado sea el vector 0. <br>

### c) (I - A) no es inversible.

Como ($I$ - $A$) no es inversible, el sistema a resolver viene dado por la ecuación $(I - A)*p = d$ y es el siguiente:
$$
\begin{cases}
l_{11}*p_1 + l_{12}*p_2 + ... + l_{1n}*p_n = d_1 \\
l_{21}*p_1 + l_{22}*p_2 + ... + l_{2n}*p_n = d_2 \\
\vdots \\
l_{n1}*p_1 + l_{n2}*p_2 + ... + l_{nn}*p_n = d_n \\
\end{cases}
$$
Al contrario del punto anterior, que la matriz ($I$ - $A$) no sea inversible implica que su determinante es igual a 0. Esto significa, que su rango será menor que $n$, por lo tanto sus filas son linealmente dependientes. Entonces, al resolver el sistema escalonando la matriz podemos tener dos situaciones:
1. Que las filas eliminadas por ser linealmente dependientes se igualen a cero, obteniendo así un sistema compatible indeterminado con infinitas soluciones para \( p \). En este caso, lo que obtendríamos es un generador del núcleo de (I-A) con sus posibles conjuntos solución que resultaran no triviales.
2. Que las filas eliminadas por ser linealmente dependientes se igualen a un número distinto de cero, lo cual haría que el sistema no tenga solución
.

### d) (I - A) no es inversible y d = 0.

Esto es un sistema homogéneo porque el término independiente
$𝑑$ es cero. Como $(I−A)$ no es inversible, el determinante de $(I−A)$ es cero, lo cual implica que el sistema tiene soluciones no triviales. Este sería el primer caso del item anterior, las filas linealmente dependientes del sistema escalonado estarían igualadas a cero generando infinitas soluciones para p. Obtenemos un sistema compatible indeterminado ya que el número de ecuaciones es menor al número de incógnitas.

### Consigna 3 -  

In [1]:
from funciones_reentrega import calcularLU, inversaLU
import numpy as np
A = np.array([[0.7, 0, -0.1],
     [-0.05, 0, -0.2],
     [-0.1, -0.15, 0.9]])
L, U, P=calcularLU(A)
inversa = inversaLU(L, U, P)
d = np.array([[100], [100], [300]])
p = inversa@d

Queremos resolver $p = (I - A)^{-1} d$ con:
$$
A = \left(\begin{matrix}
   0,3 & 0,0 & 0,1 \\
   0,05 & 1,0 & 0,2\\
   0,1 & 0,15 & 0,1
   \end{matrix}\right),
d= \left(\begin{matrix}
   100\\
   100 \\
   300
   \end{matrix}\right)
$$
utilizando inversaLU. <br>


In [2]:
print("El p obtenido fue:")
print(p)

El p obtenido fue:
[[   68.96551724]
 [-5149.42528736]
 [ -517.24137931]]


- ¿Hay una justificación económica de los valores encontrados para $p$?
- ¿Cuál es la característica de la matriz que lleva a esta solución?

Los valores negativos obtenidos en $p$ pueden interpretarse como pérdidas, déficits o salidas netas. Esto sugiere que ciertos sectores están experimentando desbalances, es decir, consumen más recursos de los que generan. Analicemos el significado de la matriz $A$. Cada fila indica cuanta demanda interna tiene cada producto. En el caso de la primera fila de la matriz: <br>
- para producir $p_1$ unidades de Producto 1 se requiere $0,3p_1$ unidades de Producto 1.
- para producir $p_2$ unidades de Producto 2 se requiere $0p_2$ unidades de Producto 1.
- para producir $p_3$ unidades de Producto 3 se requiere $0,1p_3$ unidades de Producto 1.

En la segunda fila de la matriz $A$ se puede observar un problema importante: para producir $p_2$ unidades de Producto 2 se requiere $1p_2$ unidades de Producto 2, lo cual significa que el sector no deja excedente de $p_2$. Al mismo tiempo, para producir $p_2$ unidades de Producto 2 se requiere $0,15p_2$ unidades de Producto 3. Esto genera un desbalance claro, ya que entre los sectores 2 y 3 se están consumiendo más recursos de $p_2$ de los que realmente se están generando. A medida que varios sectores consumen entre sí más de lo que pueden producir el sistema se vuelve insostenible.

### Consigna 4 -

En este punto vamos a analizar que sucede con la producción total $P$ , cuando la demanda externa cambia en un $$\triangle d= \left(\begin{matrix}
   0\\
   0 \\
   1
   \end{matrix}\right)$$



Nos encontramos con la ecuación:  $$p=(I-A)^{-1}d$$

Al modificar la demanda externa en un $\triangle d$, nuestra producción total también se modifica en un $\triangle p$. La ecuación quedaria: $$ p + \triangle p = (I-A)^{-1}(d+\triangle d) $$

Desarrollamos: $$ p + \triangle p = (I-A)^{-1}d+(I-A)^{-1}\triangle d) $$

Como $p=(I-A)^{-1}d$ : $$  \cancel{p} + \triangle p = \cancel{(I-A)^{-1}d}+(I-A)^{-1}\triangle d) $$

Entonces, en conclusión: $$  \triangle p =(I-A)^{-1}\triangle d $$

### Consigna 5 -

Queremos encontrar los coeficientes técnicos **A** y la matriz de Leontief(**L**) donde $A = ZP^{-1}$ y $L = (I - A)^{-1}$. <br>
**Z** representa la demanda interna y **P** el total producido. Matricialmente queda expresado de la siguiente manera:
$$
z = \left(\begin{matrix}
350 & 0 & 0 \\
50 & 250 & 150 \\
200 & 150 & 550
\end{matrix}\right)
\\
P = \left(\begin{matrix}
1000 & 0 & 0 \\
0 & 500 & 0 \\
0 & 0 & 1100
\end{matrix}\right)
$$
Al ser **P** una matriz diagonal su inversa es
$$
P^{-1} = \left(\begin{matrix}
1/1000 & 0 & 0 \\
0 & 1/500 & 0 \\
0 & 0 & 1/1100
\end{matrix}\right)
$$
Entonces,
$$
A = \left(\begin{matrix}
350 & 0 & 0 \\
50 & 250 & 150 \\
200 & 150 & 550
\end{matrix}\right)
\left(\begin{matrix}
1/1000 & 0 & 0 \\
0 & 1/500 & 0 \\
0 & 0 & 1/1100
\end{matrix}\right)
= \left(\begin{matrix}
0,35 & 0 & 0 \\
0,05 & 0,5 & 0,15 \\
0,2 & 0,3 & 0,55
\end{matrix}\right)
$$

Ahora calculamos **L**
$$
(I - A) = \left(\begin{matrix}
0,65 & 0 & 0 \\
-0,05 & 0,5 & -0,15 \\
-0,2 & -0,3 & 0,45
\end{matrix}\right)
$$
Por lo tanto,
$$
L = \left(\begin{matrix}
20/13 & 0 & 0 \\
35/78 & 2,5 & 5/6 \\
115/117 & 5/3 & 25/9
\end{matrix}\right)
$$

# Consigna 6


Partimos de la base que cuando nos interesa saber como es el flujo de capitales sobre una determinada región "r" y su relación con la región "s" podemos usar el modelo de Leontief para dos regiones :

$$
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)   
\left(\begin{matrix}
p^{r}\\
p^{s}\\
\end{matrix}\right)
=
\left(\begin{matrix}
d^{r}\\
d^{s}\\
\end{matrix}\right)
(1)
$$


Si sobre esta se efectúa un shock sobre la demanda, de forma que la nueva producción se vea alterada, y nos interesa saber cúal sería la producción adicional que se requiere para abastecer lo que pide la nueva demanda en la relación interregional de "r" y "s", planteamos :  

$$
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)   
\left(\begin{matrix}
p^{r'}\\
p^{s'}\\
\end{matrix}\right)
=
\left(\begin{matrix}
d^{r'}\\
d^{s'}\\
\end{matrix}\right)
$$

donde:
- $p^{r'} = p^{r} + \triangle p^{r}$
- $p^{s'} = p^{s} + \triangle p^{s}$
- $d^{r'} = d^{r} + \triangle d^{r}$
- $d^{s'} = d^{s} + \triangle d^{s}$

Desarrollo:

$$
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)   
\left(\begin{matrix}
p^{r} + \triangle p^{r}\\
p^{s} + \triangle p^{s}\\
\end{matrix}\right)
=
\left(\begin{matrix}
d^{r} + \triangle d^{r}\\
d^{s} + \triangle d^{s}\\
\end{matrix}\right)
$$

Distribuimos

$$
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)   
\left(\begin{matrix}
p^{r} \\
p^{s} \\
\end{matrix}\right)
+
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)
\left(\begin{matrix}
\triangle p^{r} \\
\triangle p^{s} \\
\end{matrix}\right)
=
\left(\begin{matrix}
d^{r} \\
d^{s} \\
\end{matrix}\right)
+
\left(\begin{matrix}
\triangle d^{r} \\
\triangle d^{s} \\
\end{matrix}\right)
$$
Si restamos la ecuación (1) a esta que obtuvimos recién, el sistema nos quedaría:
$$
\left(\begin{matrix}
\left(\begin{matrix}
   I_{nxn} & 0_{nxm}\\
    0_{mxn} & I_{mxm}\\
   \end{matrix}\right)
   -
   \left(\begin{matrix}
   A^{rr} & A^{rs}\\
   A^{sr} & A^{ss}\\
   \end{matrix}\right)   
\end{matrix}\right)
\left(\begin{matrix}
\triangle p^{r} \\
\triangle p^{s} \\
\end{matrix}\right)
=
\left(\begin{matrix}
\triangle d^{r} \\
\triangle d^{s} \\
\end{matrix}\right)
$$
Resolviendo la resta, podemos obtener una multiplicación por bloques de las matrices que componen a la matriz de insumo-producto para dos regiones; la cuál puede realizarse en el caso en que se den las condiciones básicas para multiplicar matrices, es decir que la cantidad de columnas de la matriz posicionada en la derecha sean iguales a la cantidad de filas de la matriz a la izquierda y eso dependerá de la cantidad de relaciones económicas que hayan en los sectores de una región. Teniendo en cuenta eso, podemos ver que en nuestro caso es posible, por lo que continuamos así:
$$
\left(\begin{matrix}
I_{nxn}-A^{rr} & -A^{rs} \\
-A^{sr} & I_{mxm}-A^{ss}
\end{matrix}\right)
\left(\begin{matrix}
\triangle p^{r} \\
\triangle p^{s} \\
\end{matrix}\right)
=
\left(\begin{matrix}
\triangle d^{r} \\
\triangle d^{s} \\
\end{matrix}\right)
$$
Luego la desarrollamos y reemplazando $\triangle d^{s}$ por 0, obtenemos "dos ecuaciones" para despejar $\triangle p^{r}$:
$$
(I_{nxn}-A^{rr})\triangle p^{r} + (-A^{rs})\triangle p^{s} = \triangle d^{r} (2)
$$
$$
(-A^{sr})\triangle p^{r} + (I_{mxm}-A^{ss})\triangle p^{s} = 0 (3)
$$
De la ecuación (3) obtenemos:
$$
\triangle p^{s} = (I_{mxm}-A^{ss})^{-1} (A^{sr})\triangle p^{r}
$$
Reemplazándolo en la ecuación (2), está nos queda:
$$
(I_{nxn}-A^{rr})\triangle p^{r} + (-A^{rs})(I_{mxm}-A^{ss})^{-1} (A^{sr})\triangle p^{r} = \triangle d^{r}
$$
Sacamos factor común $\triangle p^{r}$, y finalmente obtenemos el valor pedido del mismo:
$$
\triangle p^{r} = [(I_{nxn}-A^{rr})- A^{rs}I_{mxm}-A^{ss})^{-1} (A^{sr})]^{-1}\triangle d^{r}
$$

# CONSIGNA 7


Cargamos el archivo propiciado

In [3]:
import pandas as pd
data = pd.read_excel("matrizlatina2011_compressed_0.xlsx",sheet_name=1)

Para poder crear la matriz de flujo de capitales intrarregionales e interregionales de Costa Rica y Nicaragua
seguimos utilizamos los siguientes métodos de las librerias propiciadas.

In [4]:
from funciones_reentrega import generadorMatrizZ
ZCriCri = generadorMatrizZ(data,"CRI","NIC")

ZNicNic = generadorMatrizZ(data,"NIC","NIC")

ZCriNic = generadorMatrizZ(data,"CRI","NIC")

ZNicCri = generadorMatrizZ(data,"NIC","CRI")

Las producciones totales de Costa Rica por un lado, y Nicaragua por el otro

In [5]:
from funciones_reentrega import produccionesPais
pCri = produccionesPais(data,"CRI")

pNic = produccionesPais(data,"NIC")

Esta es la matriz Z de flujo de capitales de  manera intrarregional e interregional para los sectores P1 = Costa Rica y P2 = Nicaragua

In [6]:
from funciones_reentrega import ZGrande
Z = ZGrande(ZCriCri,ZCriNic,ZNicCri,ZNicNic)
print(pd.DataFrame(Z))

          0         1    2         3         4         5         6         7   \
0   1.153226  0.007047  0.0  0.000476  3.040210  0.935190  0.496777  0.174665   
1   0.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.215696  0.0  0.000000  2.857147  0.577612  0.000000  0.501390   
..       ...       ...  ...       ...       ...       ...       ...       ...   
75  0.005082  0.000000  0.0  0.000537  0.058727  0.021461  0.005617  0.062318   
76  0.009327  0.000030  0.0  0.000398  0.018129  0.003543  0.000867  0.017849   
77  0.000000  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
78  0.100966  0.001131  0.0  0.033619  0.043294  0.021918  0.023382  0.049462   
79  0.005485  0.000000  0.0  0.000861  0.006769  0.007023  0.000786  0.002903   

          8         9   ...

Para la creacion de cada matriz A insumo producto para armar la de la ecuación 4, precisamos de las siguientes matrices
construidas a partir de las siguientes funciones

In [7]:
from funciones_reentrega import IdxP, AInsumoProducto
#La siguiente variable me devuelve la matriz diagonal para hacer A= ZP1
IdPCri = IdxP(pCri)

##La siguiente variable me devuelve la matriz diagonal para hacer A= ZP2
IdPNic = IdxP(pNic)

#Calculamos sus inversas respectivamente..
L_Id_Cri, U_Id_Cri, P_Id_Cri =calcularLU(IdPCri)
IdCri_inv = inversaLU(L_Id_Cri, U_Id_Cri, P_Id_Cri)
#
L_Id_Nic, U_Id_Nic, P_Id_Nic =calcularLU(IdPNic)
IdNic_inv = inversaLU(L_Id_Nic, U_Id_Nic, P_Id_Nic)

#La Matriz de coeficientes tecnicos intrarregional: COSTA RICA-COSTA RICA
ACriCri = AInsumoProducto(ZCriCri,IdCri_inv)
#La Matriz de coeficientes tecnicos intrarregional: COSTA RICA-NICARAGUA
ACriNic = AInsumoProducto(ZCriCri,IdNic_inv)
#La Matriz de coeficientes tecnicos intrarregional: NICARAGUA- COSTA RICA
ANicCri = AInsumoProducto(ZCriCri,IdCri_inv)
#La Matriz de coeficientes tecnicos intrarregional: NICARAGUA-NICARAGUA
ANicNic = AInsumoProducto(ZCriCri,IdNic_inv)


La creacion de la Matriz A que nos aporta la información de insumo-producto en economias regionales e interregionales
 viene de parte de la siguiente función

In [8]:
from funciones_reentrega import AInsumoProductoMultiRegional
A = AInsumoProductoMultiRegional(ZCriCri,ZCriNic,ZNicCri,ZNicNic,IdCri_inv,IdNic_inv)
print(pd.DataFrame(A))

          0             1    2         3         4         5         6   \
0   0.000250  6.801845e-05  0.0  0.000004  0.001192  0.000912  0.001415   
1   0.000000  0.000000e+00  0.0  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000e+00  0.0  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000e+00  0.0  0.000000  0.000000  0.000000  0.000000   
4   0.000000  2.081949e-03  0.0  0.000000  0.001120  0.000563  0.000000   
..       ...           ...  ...       ...       ...       ...       ...   
75  0.000001  0.000000e+00  0.0  0.000004  0.000023  0.000021  0.000016   
76  0.000002  2.892776e-07  0.0  0.000003  0.000007  0.000003  0.000002   
77  0.000000  0.000000e+00  0.0  0.000000  0.000000  0.000000  0.000000   
78  0.000022  1.091509e-05  0.0  0.000254  0.000017  0.000021  0.000067   
79  0.000001  0.000000e+00  0.0  0.000007  0.000003  0.000007  0.000002   

          7             8         9   ...   70        71            72  \
0   0.000082  2.186924e-0

SIMULACIÓN DE SHOCK:
¿Cómo impactará a nuestro modelo?
Trabajaremos con un shock negativo del 10% sobre el sector 5 de las producciones de Costa Rica, y luego con un positivo del 3,3% sobre los
sectores 6, 7, y 8 del país nombrado.


In [9]:
#la demanda trabaja desde la fila 1 a la 40 sobre la region de Costa rica (indices del vector desde el 0 al 39), y de la 41 a la 80 sobre Nicaragua (indices del 40 al 79).
from funciones_reentrega import demandaSimple
demandaInter = demandaSimple(ACriCri,pNic)

MODELO DE PRODUCCIÓN INTRARREGIONAL

Utilizamos la siguiente ecuación:
$$
\triangle p^{r} = [(I_{nxn}-A^{rr})]^{-1}\triangle d^{r}
$$

Para comparar los modelos de nos propician los valores de producciones totales sobre especificamente uno de los dos paises sobre los cuales queremos trabajar
según la ecuación (5) explicitada en la consigna del trabajo, que nos ayuda a obtener el diferencial de producción de la region R, en este caso nos interesa sobre
Costa Rica. Para ello necesitamos lo siguiente:

In [10]:
demandaIntra = demandaSimple(ACriCri,pNic)

from funciones_reentrega import diferencialShock
#La primera coordenada del array de shocks sera el sector (su indice es sector -1) y luego el porcentaje del shock que queremos aplicar
shocks = [[5, -0.1],[6,0.033],[7,0.033],[8,0.033]]

#Queremos saber como sería la diferencia entre una nueva demanda tras los shocks y la demanda previa a estos.
deltaDemandaIntra = diferencialShock(demandaIntra,shocks)

display(deltaDemandaIntra)
#La demanda tras efectuar los shocks es la siguiente
nuevaDemandaIntra = demandaIntra + deltaDemandaIntra

display(nuevaDemandaIntra)

array([[   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [-138.66192482],
       [  13.92453909],
       [  10.20160672],
       [   5.74336734],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ]])

array([[ 2.72655896e+03],
       [ 1.48902921e+02],
       [ 0.00000000e+00],
       [ 9.26644312e+01],
       [ 1.24795732e+03],
       [ 4.35880269e+02],
       [ 3.19341204e+02],
       [ 1.79784802e+02],
       [ 3.90721103e+02],
       [ 1.18490740e+02],
       [ 7.24194787e+00],
       [ 8.65288648e+02],
       [ 5.23372810e+01],
       [ 7.79875799e+01],
       [ 3.10835102e+01],
       [ 6.56420583e+02],
       [ 6.25932145e+01],
       [-1.06381135e+01],
       [ 2.21097577e+01],
       [ 1.08912853e+01],
       [ 1.62343225e+02],
       [ 6.69880054e+00],
       [ 3.63216535e+02],
       [ 4.16901155e+01],
       [ 4.07310696e+02],
       [-7.91206979e-02],
       [-3.91734093e+01],
       [-3.20571924e-01],
       [-2.70235916e-02],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 5.63336340e+01],
       [ 4.08716004e+01],
       [ 6.48184808e+02],
       [ 1.31961340e+03],
       [ 7.27609213e+02],
       [ 4.59423662e+02],
       [ 6.19943375e+02],
       [ 1.2

In [11]:
#Ahora para el calculo de la producción...

idMenosACriCri = (np.eye(ACriCri.shape[0]) - ACriCri)

L_idMenosACriCri, U_idMenosACriCri, P_idMenosACriCri =calcularLU(idMenosACriCri)

IdCri_inv = inversaLU(L_idMenosACriCri, U_idMenosACriCri, P_idMenosACriCri)

#Usamos un slicing sobre el vector demanda desde el indice 0 hasta el 40 (excluyendolo), pues nos interesa trabajar sobre la producción de Costa Rica.
deltaDemandaIntraCri = deltaDemandaIntra[0:40]


In [12]:
#Y como resultado obtenemos al diferencial de producción que buscabamos usando este método.

deltaPCriIntra = IdCri_inv @ deltaDemandaIntraCri

display(deltaPCriIntra)

array([[-1.37721659e-01],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-1.38808082e+02],
       [ 1.41230291e+01],
       [ 1.01616055e+01],
       [ 5.73187481e+00],
       [-4.24529894e-07],
       [ 0.00000000e+00],
       [ 1.35196457e-03],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-7.59969951e-05],
       [-6.67482767e-02],
       [-8.20211936e-06],
       [ 5.69950930e-04],
       [-4.79843272e-02],
       [ 2.15451017e-04],
       [-1.34970201e-01],
       [-5.50498059e-03],
       [ 8.33313459e-05],
       [-2.62912249e-08],
       [-6.05599522e-03],
       [ 3.20532071e-04],
       [-2.73086757e-05],
       [ 3.61573870e-03],
       [-1.77071292e-06],
       [ 3.60274353e-06],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-5.36223087e-08],
       [-4.08106099e-04],
       [-1.56302666e-03],
       [ 0.00000000e+00],
       [-1.97048459e-03],
       [-2.62850766e-03],
       [ 0.00000000e+00],
       [-9.6

MODELO DE PRODUCCIÓN INTERREGIONAL

Utilizamos :

$$
\triangle p^{r} = [(I_{nxn}-A^{rr})- A^{rs}I_{mxm}-A^{ss})^{-1} (A^{sr})]^{-1}\triangle d^{r}
$$


Ahora utilizando el método que se apoya sobre los coeficientes tecnicos del flujo de capitales interregional entre Costa Rica y Nicaragua
según la ecuación (6), el diferencial de producción de la region de Costa Rica se calcula así:

In [13]:
'''Calculamos el diferencial en la producción causado por el shock en la demanda'''

#La diferencia es que en el modelo interregional la variable inv_idMenosA
#resulta ser suma y producto de otras matrices, a diferencia del modelo intrarregional...

'Calculamos el diferencial en la producción causado por el shock en la demanda'

In [14]:
from funciones_reentrega import demandaCompleja
demandaInter = demandaCompleja(ACriCri,ACriNic,ANicCri,ANicNic,pCri,pNic)

In [15]:
from funciones_reentrega import diferencialShock
#La primera coordenada del array de shocks sera el sector (su indice es sector -1) y luego el porcentaje del shock que queremos aplicar
shocks = [[5, -0.1],[6,0.033],[7,0.033],[8,0.033]]

#Queremos saber como sería la diferencia entre una nueva demanda tras los shocks y la demanda previa a estos.
deltaDemandaInter = diferencialShock(demandaInter,shocks)

display(deltaDemandaInter)
#La demanda tras efectuar los shocks es la siguiente
nuevaDemandaInter = demandaInter + deltaDemandaInter

display(nuevaDemandaInter)

array([[   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [-253.23214507],
       [  32.17679457],
       [  10.92951946],
       [  69.94322066],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.   

array([[ 4.60383351e+03],
       [ 1.03602891e+02],
       [ 0.00000000e+00],
       [ 1.32463793e+02],
       [ 2.27908931e+03],
       [ 1.00723118e+03],
       [ 3.42127079e+02],
       [ 2.18943476e+03],
       [ 8.27230991e+02],
       [ 4.23831816e+01],
       [ 5.84949455e+01],
       [ 2.75676076e+02],
       [ 6.93625503e+00],
       [ 1.20879571e+02],
       [ 8.56238221e+02],
       [ 1.09528500e+03],
       [ 2.72647875e+02],
       [ 4.86954199e+02],
       [ 3.84700737e+02],
       [ 7.71345321e+02],
       [ 5.76642339e+02],
       [ 1.61110451e+02],
       [ 1.38850949e+02],
       [ 3.04018659e+02],
       [ 1.90695855e+02],
       [ 4.91537808e+02],
       [ 4.67309721e+02],
       [ 4.36506365e+01],
       [ 1.23870975e+03],
       [ 3.58036634e+01],
       [ 0.00000000e+00],
       [ 5.91032808e+00],
       [ 5.00578066e+02],
       [ 1.28219581e+03],
       [ 5.46160025e+03],
       [ 2.94765050e+03],
       [ 1.61609893e+03],
       [ 3.17734241e+03],
       [ 9.7

In [24]:

#Le asigno una variable a lo que se le calcula la inversa dentro de la ecuación ya mostrada..
#CALCULAMOS PRIMERO INVERSA DE (IMXM - ANICNIC)

idMenosANicNic = (np.eye(ANicNic.shape[0]) - ANicNic)
display(idMenosANicNic)
L_idMenosANicNic, U_idMenosANicNic, P_idMenosANicNic =calcularLU(idMenosANicNic)

inv_idMenosANicNic = inversaLU(L_idMenosANicNic, U_idMenosANicNic, P_idMenosANicNic)

calculo_delta_p = ((np.eye(ACriCri.shape[0]) - ACriCri - ACriNic @ inv_idMenosANicNic) @ ANicCri)

#Calculamos la inversa de las operaciones internas
L_calculo_delta_p, U_calculo_delta_p, P_calculo_delta_p = calcularLU(calculo_delta_p)
inv_calculo_delta_p = inversaLU(L_calculo_delta_p, U_calculo_delta_p, P_calculo_delta_p)

#Como resultado obtenemos al siguiente diferencial de producción con el modelo mencionado.
deltaDemandaInterCri = deltaDemandaInter[0:40]

deltaProduccionCriInter = inv_calculo_delta_p @ deltaDemandaInterCri

display(deltaProduccionCriInter)


array([[ 9.99577668e-01, -4.73255190e-05,  0.00000000e+00, ...,
         0.00000000e+00, -7.68790107e-07, -4.24466867e-05],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.17634759e-04, -2.81558621e-04,  0.00000000e+00, ...,
        -2.19124745e-03,  9.99728614e-01, -1.15792980e-03],
       [-2.86534747e-04, -4.14879042e-04,  0.00000000e+00, ...,
        -4.94515338e-03, -9.94188477e-04,  9.95928690e-01]])

ValueError: array must not contain infs or NaNs

A simple vista podemos notar que sobre algunos sectores de la variación de producción no presentan diferencias notorias, trataremos de ver a que se debe esto.

Y también un poco de visualización nos vendría bien para analizar que diferencias se presentan en los modelos...

In [20]:
"""A continuación utilizaremos un gráfico de dispersión de puntos para poder visualizar que tanto difieren los valores de la variación
en cada producción respecto de su sector para ambos modelos"""

import matplotlib.pyplot as plt


delta_producciones = np.hstack((deltaPCriIntra, deltaProduccionCriInter))

data = pd.DataFrame(delta_producciones, columns=['deltaPCriIntra', 'deltaProduccionCriInter'])

data = data.rename(columns={'deltaPCriIntra':"Produccion_Intra",'deltaProduccionCriInter':"Produccion_Inter"})

fig, ax= plt.subplots()

plt.rcParams['font.family']= 'sans-serif'

data.plot(y= ['Prod_IntraReg','Prod_InterReg'],
                 kind= 'bar',
                 ax=ax,title="El shock que se produce en las demandas")

'\nimport matplotlib.pyplot as plt\n\nejeX = np.arange(1,41)\n\nfig ,(deltaPCriIntra, deltaPCriInter) = plt.subplots(1,2, figsize= (12, 4))\n\n#Para el del modelo intrarregional tenemos el primer subgrafico\ndeltaPCriIntra.scatter(ejeX, deltaProduccionCriIntra)\ndeltaPCriIntra.set_title("Modelo intrarregional Costa Rica")\ndeltaPCriIntra.set_xlabel("Producciones")\ndeltaPCriIntra.set_ylabel("Variación de producción")\n\n#Para el del modelo interregional tenemos el segundo subgráfico\n\ndeltaPCriInter.scatter(ejeX, deltaProduccionCriInter)\ndeltaPCriInter.set_title("Modelo relación interregional")\ndeltaPCriInter.set_xlabel("Producciones")\ndeltaPCriInter.set_ylabel("Variación de producción")\n\n#para ajustar los graficos\nplt.tight_layout()\nplt.show()\n'

En los gráficos podemos observar como la variación de la producción según el modelo utilizado no presentan una gran diferencia significativa en sus valores.

Sobre este aspecto y el resto del trabajo realizado anteriormente, podriamos decir que el aporte economico que propicia las relaciones interregionales entre Costa Rica y Nicaragua, para el resultado de las producciones del primer país es prescindible (al menos sobre los sectores trabajados, los cuáles si afectan a otros sectores.)

Aparentemente, frente a la demanda efectuada por el shock sobre el que trabajamos, las producciones totales de Costa Rica serían similares si éste tuviera o no una dinámica económica activa con Nicaragua.